In [1]:
import numpy as np

### Exercícios Sobre Módulos Python Para Análise de Dados

### Exercício 1

In [2]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

arrNp = np.arange(1000000)
lista = list(range(1000000))

# Se aumentar o range demora ainda mais
%time for _ in range(10): arrNp2 = arrNp *2
%time for _ in range(10): lista = [x * 2 for x in lista]

Wall time: 15 ms
Wall time: 820 ms


### Exercício 2

In [3]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

arr = np.arange(10)
print(arr)
arr[5:9] = 0 # o último índice é desconsiderado
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 0 0 0 0 9]


### Exercício 3

In [4]:
# Crie um array de 3 dimensões e imprima a dimensão 1 
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d.ndim)
arr3d[0]

3


array([[1, 2, 3],
       [4, 5, 6]])

### Exercício 4

In [5]:
# Crie um array de duas dimensões (matriz).

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("array: ", arr2d)
print("dimensões:", arr2d.ndim)

# Imprima os elementos da terceira linha da matriz
print("terceira linha da matriz: ", arr2d[2])

# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
print(arr2d[:2, 1:])


array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
dimensões: 2
terceira linha da matriz:  [7 8 9]
[[2 3]
 [5 6]]


### Exercício 5

In [6]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
print("Matriz: ", arr)
print("Transporta: ", arr.T)

Matriz:  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Transporta:  [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


### Exercício 6

In [7]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

### Exercício 7

In [8]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

A = np.arange(10)
np.save('array_A', A)
B = np.load('array_A.npy')
print(B)

[0 1 2 3 4 5 6 7 8 9]


### Exercício 8

In [9]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [10]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [11]:
data = resp.json()
data[0]['title']

"DEPR: Deprecate use of strings denoting units with 'M', 'Y', 'm' or 'y' in pd.to_timedelta"

In [12]:
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/36838',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/36838/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/36838/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/36838/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/36838',
  'id': 714138116,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NDk3MzExNTgw',
  'number': 36838,
  'title': "DEPR: Deprecate use of strings denoting units with 'M', 'Y', 'm' or 'y' in pd.to_timedelta",
  'user': {'login': 'avinashpancham',
   'id': 44933366,
   'node_id': 'MDQ6VXNlcjQ0OTMzMzY2',
   'avatar_url': 'https://avatars1.githubusercontent.com/u/44933366?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/avinashpancham',
   'html_url': 'https://github.com/avinashpancham',
   'followers_url': 'https://api

In [13]:
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

number                                              title  \
0    36838  DEPR: Deprecate use of strings denoting units ...   
1    36837                Add hacktoberfest topic to the repo   
2    36836  DOC: Update docs on estimated time of running ...   
3    36834  Fix/empty string datetimelike conversion/issue...   
4    36833                              REF: NDFrame describe   
5    36828  to_csv fails silently when writing to S3 (only...   
6    36827  BUG: python engine in pd.read_csv fails to use...   
7    36826                           CI add end-of-file-fixer   
8    36822  BUG: Raise ValueError with nan in timeaware wi...   
9    36820                    Issue36124 display of int enums   
10   36819                    ENH: Infer Enums as categorical   
11   36814  DOC: add example & prose of slicing with label...   
12   36808      Fix select_dtypes(include='int') for Windows.   
13   36806  BUG: resample inconsistency with closed left/r...   
14   36805                     DOC: unclear kwarg null_counts   
15   36802  DOC: ran blacken docs tool and checked output ...   
16   36800           BUG: Fix FloatingArray output formatting   
17   36799   BUG/CLN: Clean float / complex string formatting   
18   36796  API: disallow frame.__and__(other, axis="foo",...   
19   36791  How to use nrows along with chunksize in read_...   
20   36790  BUG: GroupBy.ffill()/bfill() do not return NaN...   
21   36785  BUG: Row series are broken after applying to_d...   
22   36783  Test that nan value counts are included when d...   
23   36782  BUG: replacing out of bound datetimes is not p...   
24   36777               DOC: Fix code style in documentation   
25   36775    BUG: Nullable floats can look like ints in repr   
26   36773                    DOC: Fix code block line length   
27   36771  BUG: Timedelta drops decimals if precision is ...   
28   36769  BUG: to_timedelta() won't accept all freq unit...   
29   36766          BUG: fix inconsistent col spacing in info   

                                               labels state  
0                                                  []  open  
1                                                  []  open  
2                                                  []  open  
3                                                  []  open  
4   [{'id': 13101118, 'node_id': 'MDU6TGFiZWwxMzEw...  open  
5   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
6   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
7   [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open  
8   [{'id': 42670965, 'node_id': 'MDU6TGFiZWw0MjY3...  open  
9                                                  []  open  
10  [{'id': 78527356, 'node_id': 'MDU6TGFiZWw3ODUy...  open  
11  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
12  [{'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQw...  open  
13  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
14  [{'id': 1741841389, 'node_id': 'MDU6TGFiZWwxNz...  open  
15  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
16  [{'id': 1817503692, 'node_id': 'MDU6TGFiZWwxOD...  open  
17  [{'id': 13101118, 'node_id': 'MDU6TGFiZWwxMzEw...  open  
18  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
19  [{'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOT...  open  
20  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
21  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
22  [{'id': 2822342, 'node_id': 'MDU6TGFiZWwyODIyM...  open  
23  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
24  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
25  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
26  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
27  [{'id': 49597148, 'node_id': 'MDU6TGFiZWw0OTU5...  open  
28  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
29  [{'id': 2301354, 'node_id': 'MDU6TGFiZWwyMzAxM...  open

### Exercício 10

In [14]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas

import sqlite3
import pandas as pd
query = """
CREATE TABLE GITHUB
(Number INTEGER NOT NULL,
Title VARCHAR(150),
Labels VARCHAR(255),
State VARCHAR(20)
);"""

con = sqlite3.connect('issues_github.db')
con.execute(query)
con.commit()

OperationalError: table GITHUB already exists

In [15]:
from sqlalchemy import create_engine

engine = create_engine('sqlite:///issues_github.db', echo=True)
sqlite_connection = engine.connect()

2020-10-03 16:41:43,726 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2020-10-03 16:41:43,726 INFO sqlalchemy.engine.base.Engine ()
2020-10-03 16:41:43,727 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2020-10-03 16:41:43,727 INFO sqlalchemy.engine.base.Engine ()


In [18]:
sqlite_table = 'GITHUB'
issues_save = pd.DataFrame(data, columns=['number', 'title', 'state'])
issues_save.head()
issues_save.to_sql(sqlite_table, sqlite_connection, if_exists='replace')

2020-10-03 16:42:22,117 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("GITHUB")
2020-10-03 16:42:22,118 INFO sqlalchemy.engine.base.Engine ()
2020-10-03 16:42:22,119 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("GITHUB")
2020-10-03 16:42:22,119 INFO sqlalchemy.engine.base.Engine ()
2020-10-03 16:42:22,120 INFO sqlalchemy.engine.base.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2020-10-03 16:42:22,121 INFO sqlalchemy.engine.base.Engine ()
2020-10-03 16:42:22,122 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("GITHUB")
2020-10-03 16:42:22,122 INFO sqlalchemy.engine.base.Engine ()
2020-10-03 16:42:22,124 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'GITHUB' AND type = 'table'
2020-10-03 16:42:22,124 INFO sqlalchemy.engine.base.Engine ()
2020-10-03 16:42:22,125 INFO sqlalchemy.engine.base.Engine PRAGMA main.foreign_key_list("GITHUB")
2

In [20]:
cursor = con.execute('SELECT * FROM GITHUB')
rows = cursor.fetchall()
rows

[(0,
  36838,
  "DEPR: Deprecate use of strings denoting units with 'M', 'Y', 'm' or 'y' in pd.to_timedelta",
  'open'),
 (1, 36837, 'Add hacktoberfest topic to the repo', 'open'),
 (2,
  36836,
  'DOC: Update docs on estimated time of running full asv suite',
  'open'),
 (3, 36834, 'Fix/empty string datetimelike conversion/issue 36550', 'open'),
 (4, 36833, 'REF: NDFrame describe', 'open'),
 (5,
  36828,
  'to_csv fails silently when writing to S3 (only 1 time out of 50,000)',
  'open'),
 (6,
  36827,
  'BUG: python engine in pd.read_csv fails to use header=None correctly',
  'open'),
 (7, 36826, 'CI add end-of-file-fixer', 'open'),
 (8, 36822, 'BUG: Raise ValueError with nan in timeaware windows', 'open'),
 (9, 36820, 'Issue36124 display of int enums', 'open'),
 (10, 36819, 'ENH: Infer Enums as categorical', 'open'),
 (11,
  36814,
  'DOC: add example & prose of slicing with labels when index has duplicate labels ',
  'open'),
 (12, 36808, "Fix select_dtypes(include='int') for Window

In [ ]:
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>